version: '3.8'

services:
  web:
    build: ./client
    container_name: zippyx-client
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
        - action: rebuild
          path: ./client/package*.json

  api:
    build: ./server
    container_name: zippyx-server
    command: npm run dev
    ports:
      - '3000:3000'
    env_file:
      - ./server/.env
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package*.json

  db:
    image: mongo:latest
    container_name: mongodb
    command:
      ['--quiet', '--logpath', '/dev/null', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:
